name: Cross-Version

on: [push, pull_request]

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always

jobs:

  java_17:

    name: Java 17
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Test
        run: ./mvnw $MAVEN_ARGS verify

  java:

    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [22]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
          version: latest
      - name: Test
        run: ./mvnw $MAVEN_ARGS verify

  spring_boot:

    name: Spring Boot ${{ matrix.spring }}
    strategy:
      fail-fast: false
      matrix:
        spring: [3.0.0, 3.0.13, 3.1.0, 3.1.7]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Set Spring Boot ${{ matrix.spring }}
        run: >
          ./mvnw $MAVEN_ARGS versions:update-parent
          -DparentVersion=${{ matrix.spring }}
          -DskipResolution
      - name: Test
        run: ./mvnw $MAVEN_ARGS -Pspring-milestone verify
