name: Cross-Version

on: [push, pull_request]

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always -Djacoco.skip=true

jobs:

  test_java:

    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [20, 21, 22]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
          version: latest
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test
        run: ./gradlew build

  test_spring_boot:

    name: Spring Boot ${{ matrix.spring }}
    strategy:
      fail-fast: false
      matrix:
        spring: [3.0.0, 3.0.9, 3.1.0]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test
        run: ./gradlew build -PspringBootVersion=${{ matrix.spring }}
